version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ape"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-riae5mjcbmbb"
s3_prefix = "ape"
region = "us-west-2"
profile = "hsc"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
